### ISSUE TITLE
Would you mind release the model parameters and docT5query generated database?

### ISSUE THREAD

**Issue by Rui-Fang** [ArvinZhuang/DSI-QG#9]
I'm working on the model compression following this work, but finetuning two T5-Large is very expensive (for me).
Is it possible to release the model parameters, and the query database generated by docT5Query? 
That can be a great help to me and many others.

Sorry if this is a bit abrupt. Thank you so much!

**Comment by ArvinZhuang** [comment]
Hi @Rui-Fang , thanks for raising this up! Im not 100% sure I can find those model checkpoints as it has been a while and I have changed my institution (I lost access right to the machine), but I will try to help as much as I can. I will take a look this week.

**Comment by Rui-Fang** [comment]
> Hi @Rui-Fang , thanks for raising this up! Im not 100% sure I can find those model checkpoints as it has been a while and I have changed my institution (I lost access right to the machine), but I will try to help as much as I can. I will take a look this week.

Thanks!!

**Comment by ArvinZhuang** [comment]
Hi @Rui-Fang, unfortunately, I couldn't find my DSI model checkpoints.. I only have the multilingual docT5query model, do you want this model?

**Comment by Rui-Fang** [comment]
Yes! Thank you very much.

**Comment by ArvinZhuang** [comment]
Hi @Rui-Fang I have uploaded a mt5-base QG model on huggingface, check out the usage [here](https://huggingface.co/ielabgroup/xor-tydi-docTquery-mt5-base). I'm also uploading a large model, you will find it under the organization repo later.
Please note the prompt used for this model is slightly different from the prompt used in this repo, if you want to use this huggingface checkpoints to do the query generation with the code in this repo, please change the prompt in this [line](https://github.com/ArvinZhuang/DSI-QG/blob/479d8d74f9b6c83de99a6723d769e23f1402a8ba/data.py#L71) to match prompt in the model card.

**Comment by Rui-Fang** [comment]
> Hi @Rui-Fang I have uploaded a mt5-base QG model on huggingface, check out the usage [here](https://huggingface.co/ielabgroup/xor-tydi-docTquery-mt5-base). I'm also uploading a large model, you will find it under the organization repo later. Please note the prompt used for this model is slightly different from the prompt used in this repo, if you want to use this huggingface checkpoints to do the query generation with the code in this repo, please change the prompt in this [line](https://github.com/ArvinZhuang/DSI-QG/blob/479d8d74f9b6c83de99a6723d769e23f1402a8ba/data.py#L71) to match prompt in the model card.

Got it, Thanks!
